version: "3.3"
services:
  web:
    image: websyncplay/websyncplay
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SITE_NAME: ${SITE_NAME}
      PUBLIC_DOMAIN: ${PUBLIC_DOMAIN}